### ISSUE TITLE
Dodać `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by grzegorzpokorski** [Frontlive/Start-Coding#55]
Obecnie konfiguracja projektu może być dla niektórych osób trochę enigmatyczna. Projekt posiada pliki `.env*` z wymaganymi zmiennymi środowiskowymi do ustawienia, lecz nie do końca jasne jest to, co ma się w nich znaleźć. Plik z przykładową pełną konfiguracją (nie musi zawierać prawdziwych danych) znacznie ułatwiłby potencjalnym kontrybutorom konfigurację projektu oraz rozpoczęcie pracy nad nim.

**Comment by MarcinParda** [comment]
https://github.com/Frontlive/Start-Coding/pull/97
